[package]
name = "bootstrap"
version = "0.1.0"
edition = "2021"
links = "handler"

[dependencies]
lambda_runtime = "0.13.0"
serde = "1"
tokio = { version = "1", features = ["macros"] }

[build-dependencies]
cc = "1.2.16"